### ISSUE TITLE
What about the Dynamic-Kernel-Principal-Component-Analysis-DKPCA?

### ISSUE THREAD

**Issue by FZenjoys** [iqiukp/Kernel-Principal-Component-Analysis--KPCA#1]
Thanks for your great algorithm of KPCA（with Fault Diagnosis）. It's owesome to solve the nonlinear problem.
    When I rethink the algorithm, I think of that the algorithm belongs to Static KPCA，what if develop a dynamic KPCA method? It seems that there will be a more accurate diagnosis. So I try it. 
    But I failed to finish it (maybe because I do a wrong thing while making the  augmented matrix ). 
Sincerely, can you make a further step to realize the algorithm of dynamic KPCA?
Thanks again for your great work!

**Comment by FZenjoys** [comment]
Here are some references:
1. Mingxing Jia ⁎, Fei Chu.On-line batch process monitoring using batch dynamic kernel principal component analysis(J).
[On-line batch process monitoring using batch dynamic kernel principal component analysis.pdf](https://github.com/iqiukp/Kernel-Principal-Component-Analysis-KPCA/files/3089424/On-line.batch.process.monitoring.using.batch.dynamic.kernel.principal.component.analysis.pdf)


2. Ines Jaffel a, OkbaTaouali. Moving window KPCA with reduced complexity for nonlinear dynamic process monitorin(J).
[Moving window KPCA with reduced complexity for nonlinear dynamic process monitoring.pdf](https://github.com/iqiukp/Kernel-Principal-Component-Analysis-KPCA/files/3089416/Moving.window.KPCA.with.reduced.complexity.for.nonlinear.dynamic.process.monitoring.pdf)

3. YUAN Zhe，SHI Huaitao. Fault Diagnosis Approach Based on Step Dynamic KPCA(J)
[√基于分步动态核主元分析的故障诊断方法.pdf](https://github.com/iqiukp/Kernel-Principal-Component-Analysis-KPCA/files/3089414/default.pdf)

**Comment by iqiukp** [comment]
Thanks for your support. I have already added Dynamic KPCA in the latest version.

**Comment by FZenjoys** [comment]
Your efficiency is really high. Thanks for your reply and the effective algorithm.
By the way, I should do more practice on KPCA.
Good Night.
