### ISSUE TITLE
thank you for your wonderful work,,It would be nice to have a python version here

### ISSUE THREAD

**Issue by xixi911** [iqiukp/Kernel-Principal-Component-Analysis--KPCA#2]

**Comment by xixi911** [comment]
for the fault identification,  if the theta euqal to one ,is it equivalent to the traditional partial differential fault location method? like the method in "Fault identification for process monitoring using kernel principal component analysis"

**Comment by iqiukp** [comment]
Thanks for your support. 

 _’ It would be nice to have a python version‘._

This may be difficult for me, but I will consider writing a python version of KPCA  in a later version.

_’ for the fault identification, if the theta equal to one, is it equivalent to the traditional partial differential fault location method?‘_

For fault identification,  I use the code provided by others. For details of this algorithm, please refer to this paper: 
  [1]  Deng X, Tian X. A new fault isolation method based on unified
        contribution plots[C]//Proceedings of the 30th Chinese Control 
        Conference. IEEE, 2011: 4280-4285.
To be honest, I only tested the validity of this part of the code through some experiments, but I didn't study the algorithm carefully.

**Comment by xixi911** [comment]
ok，thanks for your reply！
