### ISSUE TITLE
some problem occur in demoFaultDiagnosis

### ISSUE THREAD

**Issue by 31LouXiaXiaoHei** [iqiukp/Kernel-Principal-Component-Analysis--KPCA#3]
### the program repot error when i run demoFaultDiagnosis 
here is error reporting 
```
类 'Kernel' 没有恰当的方法、属性或字段 'width'。

出错 KpcaTestFaultDetection/test (line 72)
                         testresult.width = model.kernel.width;

出错 KpcaModel/test (line 33)
            testresult = testtype.test(obj, kpcamodel, testdata);

出错 demoFaultDiagnosis (line 71)
           testresult = kpca.test(model, testdata);
```
I am so poor in matlab, that i can not debug bymyself .
**I will be very grateful to you, if  you help me solve this problem .**

**Comment by iqiukp** [comment]
Sorry for this error. I have fixed it in the latest file.

**Comment by 31LouXiaXiaoHei** [comment]
> Sorry for this error. I have fixed it in the latest file.

thanks for your help,now program run well.
this program do a lot help in my thesis。
thank you very much
