### ISSUE TITLE
kpca.test(testdata);

### ISSUE THREAD

**Issue by add5664** [iqiukp/Kernel-Principal-Component-Analysis--KPCA#4]
hi,dear. when i use teprocess data. traindata is 52*500 and  testdata is 960*52.
it turns out that            Kernel/gaussian (line 86) xy = 2*x*y';
and how should i put it right ?

**Comment by add5664** [comment]
我试了480*52 的训练集和960*52的测试集，从图来说结果应该是出问题了。
警告: 对于非对称和复数问题，必须具有 k < n-1 的特征值数量。
使用 eig。 
> In eigs/checkInputs (line 844)
  In eigs (line 97)
  In KernelPCA/computeEigenvalue (line 167)
  In KernelPCA/train (line 46)
  In demo_FD (line 19)

**Comment by iqiukp** [comment]
你好。尝试把KernelPCA/computeEigenvalue的这行代码“[V, D] = eigs(K_c/obj.model.n_samples, obj.model.dim);”

替换为以下几行：
[V,  D] = eig(K_c/obj.model.n_samples) ;
V = V(:, 1:obj.model.dim);
D = D(1:obj.model.dim, 1:obj.model.dim);

其他地方不用修改。看看是否还报错。但是你的数据量很大，利用eig特征分解可能会效率很低。

**Comment by add5664** [comment]
我昨天试了您提供的方法，不报错了但是图像画出来和我预期的不太一样（从160开始并没有超过控制限），我还想请问一下您的TE训练集和测试集选用的是哪组，画出来您提供的那个图片。（我数据集已经标准化处理了，高斯带宽参数是128）

**Comment by iqiukp** [comment]
有可能是因为MATLAB版本问题。eig函数在早期版本的特征值以及对应的特征向量不是按照从大到小排序的。我把这个 KernelPCA/computeEigenvalue这个类方法再补充一下这种情况的代码吧。另外，TE数据我用的应该是d00.dat和d01_te.dat这两个。

**Comment by iqiukp** [comment]
另外，数据标准化处理要注意这个：
步骤1：计算训练集的均值和标准差，对其进行标准化处理
步骤2：利用训练集的均值和标准差对测试集进行标准化处理

对于其他组的TE数据，注意同时调整一下高斯核参数。

**Comment by add5664** [comment]
问题解决了，感谢感谢，是我标准化的有问题！
祝身体健康，工作顺利。
