### ISSUE TITLE
Dynamic KPCA(DKPCA)

### ISSUE THREAD

**Issue by Ayubirad** [iqiukp/Kernel-Principal-Component-Analysis--KPCA#5]
Hi there,

First of all thanks for the function. On 18 Apr 2019 you've mentioned that DKPCA is added to the code but I cannot seem to find it. Please, would you help me out on how to use it?

Best regards,

**Comment by iqiukp** [comment]
Hi. In the new version, DKPCA has been removed. You can use it in Releases v2.0.

**Comment by Wang-zhechao** [comment]
Hello,
 thank you for your contribution to the open source code. However, when I use fault 1 in te data for detection, I found that the T2 of KPCA can not detect the fault, but PCA can. Would you like to ask whether there is an error in the code?
![Snipaste_2020-08-07_15-48-13](https://user-images.githubusercontent.com/55741988/89622355-8208e780-d8c5-11ea-9bbd-89c454343dc2.png)
[d01_te_melta.xlsx](https://github.com/iqiukp/Kernel-Principal-Component-Analysis-KPCA/files/5040002/d01_te_melta.xlsx)
[d01_te_zscore.xlsx](https://github.com/iqiukp/Kernel-Principal-Component-Analysis-KPCA/files/5040003/d01_te_zscore.xlsx)

**Comment by iqiukp** [comment]
> Hello,
> thank you for your contribution to the open source code. However, when I use fault 1 in te data for detection, I found that the T2 of KPCA can not detect the fault, but PCA can. Would you like to ask whether there is an error in the code?
> ![Snipaste_2020-08-07_15-48-13](https://user-images.githubusercontent.com/55741988/89622355-8208e780-d8c5-11ea-9bbd-89c454343dc2.png)
> [d01_te_melta.xlsx](https://github.com/iqiukp/Kernel-Principal-Component-Analysis-KPCA/files/5040002/d01_te_melta.xlsx)
> [d01_te_zscore.xlsx](https://github.com/iqiukp/Kernel-Principal-Component-Analysis-KPCA/files/5040003/d01_te_zscore.xlsx)

Hi. Try the following adjustments:
1) Adjust the value of the kernel width.
2) Do not use the "zscore" function directly to standardize the test data. You should utilize the mean and standard deviation of the training data to standardize the test data.

**Comment by SYQsyq715** [comment]
Hi ，
First of all thanks for the function. I found that the DKPCA in version 2.0, you added a timelag to the structure. of application，but I cannot found “timelag”in anywhere else.SO what is the function of this timelag and how does it implement dynamic?
Best regards,

**Comment by iqiukp** [comment]
> Hi ，
> First of all thanks for the function. I found that the DKPCA in version 2.0, you added a timelag to the structure. of application，but I cannot found “timelag”in anywhere else.SO what is the function of this timelag and how does it implement dynamic?
> Best regards,

Hi,
The parameter 'timelag' is applied to construct the time lag Matrix (DKPCA). You can read the code of the function ".\kpca-v2.0.2\KpcaModel\constructTimelagMatrix.m" to understand its application.

**Comment by SYQsyq715** [comment]
> Hi ，
> First of all thanks for the function. I found that the DKPCA in version 2.0, you added a timelag to the structure. of application，but I cannot found “timelag”in anywhere else.SO what is the function of this timelag and how does it implement dynamic?
> Best regards,
> 
> Hi,
> The parameter 'timelag' is applied to construct the time lag Matrix (DKPCA). You can read the code of the function ".\kpca-v2.0.2\KpcaModel\constructTimelagMatrix.m" to understand its application.

Thanks a lot!
