### ISSUE TITLE
cite your paper for thanks

### ISSUE THREAD

**Issue by 31LouXiaXiaoHei** [iqiukp/Kernel-Principal-Component-Analysis--KPCA#6]
我想在我的参考文献里引用你写的论文以示感谢，方便告诉我你的论文吗？ 
I would like to thank you for quoting your paper in my references. Is it convenient to tell me your paper?

**Comment by iqiukp** [comment]
你好，谢谢你的支持。我暂时没有做KPCA相关的工作，该KPCA代码也是纯属分享心得。

**Comment by 31LouXiaXiaoHei** [comment]
OK，感谢分享
